#!/bin/bash

word1=id
word2=next
word3=manager

echo "Target Package: $word1.$word2.$word3"

find . -type f -name "*.java" -exec sed -i "s/id\.thre\.term/com\.rifsxd\.ksunext/g" {} +
find . -type f -name "*.kt" -exec sed -i "s/id\.thre\.term/com\.rifsxd\.ksunext/g" {} +

find . -depth -type d -name 'com' -execdir mv {} "$word1" \;
find . -depth -type d -name 'rifsxd' -execdir mv {} "$word2" \;
find . -depth -type d -name 'ksunext' -execdir mv {} "$word3" \;

find . -type f -exec sed -i \
    -e "s/com\.rifsxd\.ksunext/$word1.$word2.$word3/g" \
    -e "s/com\/rifsxd\/ksunext/$word1\/$word2\/$word3/g" \
    -e "s/com_rifsxd_ksunext/${word1}_${word2}_${word3}/g" {} +

if [ -f "./build.gradle.kts" ]; then
    sed -i 's/\(val managerVersionName by extra(getVersionName())\)/\1\nval managerVersionNameSpoofed = "${managerVersionName}-enjoy"/' ./build.gradle.kts
    sed -i 's/\(versionName = managerVersionName\)/versionName = managerVersionNameSpoofed/' ./build.gradle.kts
fi

if [ -f "./app/build.gradle.kts" ]; then
    sed -i '/val managerVersionName:/a val managerVersionNameSpoofed = "${managerVersionName}-enjoy"' ./app/build.gradle.kts
    sed -i 's/outputFileName = "KernelSU_Next_${managerVersionName}_${managerVersionCode}-\$name.apk"/outputFileName = "KernelSU_Next_${managerVersionNameSpoofed}_${managerVersionCode}-\$name.apk"/' ./app/build.gradle.kts
fi

echo "Done!"
